version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

  ### Workspace Utilities ##################################
  core:
    image: iatcore:latest
    volumes:
      - ../:/var/www:cached
      - ./core/logs/nginx/:/var/log/nginx
      - ./core/sites/:/etc/nginx/conf.d
      - ./core/php/php.ini:/usr/local/etc/php/php.ini
      - ./core/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./core/certs/:/etc/nginx/certs:ro
    ports:
      - "${NGINX_HOST_HTTP_PORT}:8080"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - backend


  ### MySQL Database ###########################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  ### Fake SMTP Server #############################################
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - ${MAILCATCHER_HTTP_PORT}:1080
      - ${MAILCATCHER_SMTP_PORT}:1025
    networks:
      - backend